django_flask_samples/skylines-master/skylines/frontend/forms/__init__.py
# flake8: noqa

from .aircraft_model import AircraftModelSelectField
from .club import ChangeClubForm, CreateClubForm, EditClubForm
from .file import MultiFileField
from .flight import ChangePilotsForm, ChangeAircraftForm
from .pilot import (
    ChangePasswordForm, CreatePilotForm, CreateClubPilotForm, EditPilotForm,
    RecoverStep1Form, RecoverStep2Form, LoginForm, LiveTrackingSettingsForm
)
from .upload import UploadForm, UploadUpdateForm

django_flask_samples/skylines-master/skylines/frontend/forms/aircraft_model.py
from flask.ext.babel import _

from .select import GroupSelectField
from skylines.model import AircraftModel


class AircraftModelSelectField(GroupSelectField):
    def __init__(self, *args, **kwargs):
        super(AircraftModelSelectField, self).__init__(*args, **kwargs)
        self.coerce = int

        if not kwargs.get('_form'):
            self.process(None)

    def process(self, *args, **kwargs):
        models = AircraftModel.query() \
            .order_by(AircraftModel.kind) \
            .order_by(AircraftModel.name) \
            .all()

        gliders = [(model.id, model) for model in models if model.kind == 1]
        motor_gliders = [(model.id, model) for model in models if model.kind == 2]
        hanggliders = [(model.id, model) for model in models if model.kind == 3]
        paragliders = [(model.id, model) for model in models if model.kind == 4]
        ul_gliders = [(model.id, model) for model in models if model.kind == 5]

        self.choices = []

        if len(gliders) > 0: self.choices.append((_('Gliders'), gliders))
        if len(motor_gliders) > 0: self.choices.append((_('Motor Gliders'), motor_gliders))
        if len(hanggliders) > 0: self.choices.append((_('Hanggliders'), hanggliders))
        if len(paragliders) > 0: self.choices.append((_('Paragliders'), paragliders))
        if len(ul_gliders) > 0: self.choices.append((_('UL Gliders'), ul_gliders))

        self.choices.append((_('Other'), [(0, '[unspecified]')]))

        super(AircraftModelSelectField, self).process(*args, **kwargs)

django_flask_samples/skylines-master/skylines/frontend/forms/club.py
from flask.ext.babel import lazy_gettext as l_
from flask_wtf import Form

from wtforms import TextField, SelectField
from wtforms.validators import InputRequired, URL, ValidationError, Optional

from skylines.model import Club


class ClubsSelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(ClubsSelectField, self).__init__(*args, **kwargs)
        self.coerce = int

    def process(self, *args, **kwargs):
        users = Club.query().order_by(Club.name)
        self.choices = [(0, '[' + l_('No club') + ']')]
        self.choices.extend([(user.id, user) for user in users])

        super(ClubsSelectField, self).process(*args, **kwargs)


class ChangeClubForm(Form):
    club = ClubsSelectField(l_('Club'))


class CreateClubForm(Form):
    name = TextField(l_('Name'), validators=[InputRequired()])

    def validate_name(form, field):
        if Club.exists(name=field.data):
            raise ValidationError(l_('A club with this name exists already.'))


class EditClubForm(Form):
    name = TextField(l_('Name'), validators=[InputRequired()])
    website = TextField(l_('Website'), validators=[Optional(), URL()])

    def validate_name(form, field):
        if field.data == field.object_data:
            return

        if Club.exists(name=field.data):
            raise ValidationError(l_('A club with this name exists already.'))

django_flask_samples/skylines-master/skylines/frontend/forms/file.py
from flask_wtf.file import FileField
from wtforms.widgets import FileInput as _FileInput


class FileInput(_FileInput):
    def __init__(self, multiple=False):
        self.multiple = multiple

    def __call__(self, field, **kwargs):
        if self.multiple:
            kwargs['multiple'] = 'multiple'

        return super(FileInput, self).__call__(field, **kwargs)


class MultiFileField(FileField):
    widget = FileInput(multiple=True)

django_flask_samples/skylines-master/skylines/frontend/forms/flight.py
from flask.ext.babel import lazy_gettext as l_
from flask_wtf import Form

from wtforms import TextField
from wtforms.validators import Length
from wtforms.fields import IntegerField
from wtforms.widgets import HiddenInput

from .pilot import ClubPilotsSelectField
from .aircraft_model import AircraftModelSelectField
from .validators import CompareTo, CheckPilot


class FlightForm(Form):
    id = IntegerField(widget=HiddenInput())


class ChangePilotsForm(FlightForm):
    pilot_id = ClubPilotsSelectField(l_('Pilot'), validators=[
        CheckPilot('id', message=l_('Pilot is already airborne in another flight.')),
    ])
    pilot_name = TextField(l_(u'Pilot name'))
    co_pilot_id = ClubPilotsSelectField(l_('Co-Pilot'), validators=[
        CompareTo(
            'pilot_id',
            cmp=(lambda x, y: x == 0 or x != y),
            message=l_('Pilot and co-pilot can not be the same person.')
        ),
        CheckPilot('id', message=l_('Co-Pilot is already airborne in another flight.')),
    ])
    co_pilot_name = TextField(l_(u'Co-Pilot name'))


class ChangeAircraftForm(FlightForm):
    model_id = AircraftModelSelectField(l_('Aircraft Model'))
    registration = TextField(l_('Aircraft Registration'), validators=[
        Length(max=32),
    ])
    competition_id = TextField(l_('Competition Number'), validators=[
        Length(max=5),
    ])

django_flask_samples/skylines-master/skylines/frontend/forms/units.py
from wtforms import SelectField

from skylines.lib.formatter import units


class UnitSelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(SelectField, self).__init__(*args, **kwargs)
        self.coerce = int
        self.choices = list(enumerate(x[0] for x in self.unit_registry))


class DistanceUnitSelectField(UnitSelectField):
    unit_registry = units.DISTANCE_UNITS


class SpeedUnitSelectField(UnitSelectField):
    unit_registry = units.SPEED_UNITS


class LiftUnitSelectField(UnitSelectField):
    unit_registry = units.LIFT_UNITS


class AltitudeUnitSelectField(UnitSelectField):
    unit_registry = units.ALTITUDE_UNITS


class UnitsPresetSelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(UnitsPresetSelectField, self).__init__(*args, **kwargs)
        self.coerce = int
        self.choices = list(enumerate(x[0] for x in units.UNIT_PRESETS))

django_flask_samples/skylines-master/skylines/api/views/search.py
from flask import Blueprint
from webargs import fields
from webargs.flaskparser import use_args

from skylines.model import User, Club, Airport
from skylines.model.search import (
    combined_search_query, text_to_tokens, escape_tokens
)
from .json import jsonify

search_blueprint = Blueprint('search', 'skylines')

MODELS = [User, Club, Airport]

SEARCH_ARGS = {'q': fields.Str(required=True)}


@search_blueprint.route('/search')
@use_args(SEARCH_ARGS)
def index(args):
    search_text = args['q']

    # Split the search text into tokens and escape them properly
    tokens = text_to_tokens(search_text)
    tokens = escape_tokens(tokens)

    # Create combined search query
    query = combined_search_query(MODELS, tokens)

    # Perform query and limit output to 20 items
    results = query.limit(20).all()

    results = map(convert, results)

    return jsonify(results)


def convert(old):
    new = {'type': old[0].lower(), 'id': old[1], 'name': old[2]}

    if old[0] == 'User':
        pass

    elif old[0] == 'Club':
        new['website'] = old[3][0]

    elif old[0] == 'Airport':
        new['icao'] = old[3][0]
        new['frequency'] = old[3][1]

    return new

django_flask_samples/skylines-master/skylines/api/views/user.py
from flask import Blueprint, request

from skylines.model import User
from skylines.api.oauth import oauth
from skylines.api.schemas import current_user_schema
from skylines.api.views.json import jsonify

user = Blueprint('user', 'skylines')


@user.route('/user/')
@user.route('/user')
@oauth.required()
def read():
    user = User.get(request.user_id)
    result = current_user_schema.dump(user)
    return jsonify(result.data)

django_flask_samples/skylines-master/skylines/frontend/assets/__init__.py
# flake8: noqa

from .environment import Environment

django_flask_samples/skylines-master/skylines/frontend/templates/__init__.py
# -*- coding: utf-8 -*-
"""Templates package for the application."""

django_flask_samples/skylines-master/skylines/frontend/views/__init__.py
from .errors import register as register_error_handlers
from .i18n import register as register_i18n
from .login import register as register_login

from .about import about_blueprint, about
from .assets import assets_blueprint
from .cesium import cesium_blueprint
from .club import club_blueprint
from .clubs import clubs_blueprint
from .files import files_blueprint
from .flight import flight_blueprint
from .flights import flights_blueprint
from .livetrack24 import lt24_blueprint
from .notifications import notifications_blueprint
from .ranking import ranking_blueprint
from .search import search_blueprint
from .settings import settings_blueprint
from .statistics import statistics_blueprint
from .timeline import timeline_blueprint
from .track import track_blueprint
from .tracking import tracking_blueprint
from .upload import upload_blueprint
from .user import user_blueprint
from .users import users_blueprint
from .widgets import widgets_blueprint


def register(app):
    register_error_handlers(app)
    register_i18n(app)
    register_login(app)

    app.register_blueprint(about_blueprint, url_prefix='/about')
    app.register_blueprint(assets_blueprint)
    app.register_blueprint(cesium_blueprint, url_prefix='/cesium')
    app.register_blueprint(club_blueprint, url_prefix='/clubs/<club_id>')
    app.register_blueprint(clubs_blueprint, url_prefix='/clubs')
    app.register_blueprint(files_blueprint, url_prefix='/files')
    app.register_blueprint(flight_blueprint, url_prefix='/flights/<flight_id>')
    app.register_blueprint(flights_blueprint, url_prefix='/flights')
    app.register_blueprint(lt24_blueprint)
    app.register_blueprint(notifications_blueprint, url_prefix='/notifications')
    app.register_blueprint(ranking_blueprint, url_prefix='/ranking')
    app.register_blueprint(search_blueprint, url_prefix='/search')
    app.register_blueprint(settings_blueprint, url_prefix='/settings')
    app.register_blueprint(statistics_blueprint, url_prefix='/statistics')
    app.register_blueprint(timeline_blueprint, url_prefix='/timeline')
    app.register_blueprint(track_blueprint, url_prefix='/tracking/<user_id>')
    app.register_blueprint(tracking_blueprint, url_prefix='/tracking')
    app.register_blueprint(upload_blueprint, url_prefix='/flights/upload')
    app.register_blueprint(user_blueprint, url_prefix='/users/<user_id>')
    app.register_blueprint(users_blueprint, url_prefix='/users')
    app.register_blueprint(widgets_blueprint, url_prefix='/widgets')

    @app.route('/')
    def index():
        return about()

django_flask_samples/skylines-master/skylines/frontend/views/about.py
import os.path

from flask import Blueprint, render_template, current_app
from flask.ext.babel import _

from skylines.lib.helpers import markdown

about_blueprint = Blueprint('about', 'skylines')


@about_blueprint.route('/')
def about():
    return render_template('about.jinja')


@about_blueprint.route('/imprint')
def imprint():
    content = current_app.config.get(
        'SKYLINES_IMPRINT',
        'Please set the `SKYLINES_IMPRINT` variable in the config file.')

    content = markdown.convert(content)

    return render_template(
        'generic/page.jinja', title=_('Imprint'), content=content)


@about_blueprint.route('/team')
def skylines_team():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'AUTHORS.md')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = content.replace('Developers', _('Developers'))
    content = content.replace('Translators', _('Translators'))

    content = markdown.convert(content)

    return render_template('generic/page.jinja',
                           title=_('The SkyLines Team'),
                           content=content)


@about_blueprint.route('/license')
def license():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'LICENSE')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = '<pre>' + content + '</pre>'

    return render_template(
        'generic/page.jinja', title=_('License'), content=content)

django_flask_samples/skylines-master/skylines/frontend/views/assets.py
from flask import Blueprint, current_app, send_from_directory

assets_blueprint = Blueprint('assets', 'skylines')


@assets_blueprint.route('/<path:filename>')
def static(filename):
    return send_from_directory(current_app.config.get('ASSETS_LOAD_DIR'), filename)


@assets_blueprint.route('/assets/<path:filename>')
def assets(filename):
    return send_from_directory(current_app.config.get('ASSETS_DIRECTORY'), filename)

django_flask_samples/skylines-master/skylines/frontend/views/cesium.py
from flask import Blueprint, current_app, send_from_directory
import os

cesium_blueprint = Blueprint('cesium', 'skylines')


@cesium_blueprint.route('/<path:filename>')
def index(filename):
    path = current_app.config.get('SKYLINES_CESIUM_PATH')
    path += '/' + os.path.dirname(filename) + '/'
    filename = os.path.basename(filename)

    return send_from_directory(path, filename)

django_flask_samples/skylines-master/skylines/frontend/views/club.py
from flask import Blueprint, render_template, g, redirect, url_for, abort
from sqlalchemy import func

from skylines.database import db
from skylines.frontend.forms import EditClubForm
from skylines.lib.dbutil import get_requested_record
from skylines.model import User, Club

club_blueprint = Blueprint('club', 'skylines')


@club_blueprint.url_value_preprocessor
def _pull_user_id(endpoint, values):
    g.club_id = values.pop('club_id')
    g.club = get_requested_record(Club, g.club_id)


@club_blueprint.url_defaults
def _add_user_id(endpoint, values):
    if hasattr(g, 'club_id'):
        values.setdefault('club_id', g.club_id)


@club_blueprint.route('/')
def index():
    return render_template(
        'clubs/view.jinja', active_page='settings', club=g.club)


@club_blueprint.route('/pilots')
def pilots():
    users = User.query(club=g.club).order_by(func.lower(User.name))

    return render_template(
        'clubs/pilots.jinja', active_page='settings',
        club=g.club, users=users)


@club_blueprint.route('/edit', methods=['GET', 'POST'])
def edit():
    if not g.club.is_writable(g.current_user):
        abort(403)

    form = EditClubForm(obj=g.club)
    if form.validate_on_submit():
        return edit_post(form)

    return render_template('clubs/edit.jinja', form=form)


def edit_post(form):
    g.club.name = form.name.data
    g.club.website = form.website.data
    db.session.commit()

    return redirect(url_for('.index'))

django_flask_samples/skylines-master/skylines/frontend/views/clubs.py
from flask import Blueprint, render_template
from sqlalchemy import func
from skylines.model import Club

clubs_blueprint = Blueprint('clubs', 'skylines')


@clubs_blueprint.route('/')
def index():
    clubs = Club.query().order_by(func.lower(Club.name))
    return render_template(
        'clubs/list.jinja', active_page='settings', clubs=clubs)

django_flask_samples/skylines-master/skylines/frontend/views/errors.py
from flask import render_template
from werkzeug.exceptions import (
    HTTPException, InternalServerError, RequestTimeout,
)


def register(app):
    """ Register error handlers on the given app """

    @app.errorhandler(400)
    @app.errorhandler(404)
    @app.errorhandler(500)
    def handle_error(e):
        if not isinstance(e, HTTPException):
            e = InternalServerError()

        return render_template(
            'error.jinja',
            code=e.code,
            name=e.name,
            description=e.description,
        ), e.code

    @app.errorhandler(EOFError)
    def handle_eof_error(e):
        return handle_error(RequestTimeout())

django_flask_samples/skylines-master/skylines/frontend/templates/search/list.jinja
{% from "macros/links.jinja" import club_link %}

{% extends "base-page.jinja" %}

{% set active_page = "search" %}

{% block title -%}
{% if search_text -%}
{% trans %}Search <small>for "{{ search_text }}"</small>{% endtrans %}
{%- else -%}
{% trans %}Search{% endtrans %}
{%- endif %}
{%- endblock %}


{% block content -%}
<div class="row">
  <form action="{{ url_for('search.index') }}" class="" role="search">
    <div class="col-sm-9">
      <div class="form-group">
        <input type="text" name="text" value="{{ (search_text or '')|e }}" placeholder="{{ _('Search') }}" class="form-control">
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <input type="submit" value="Search" class="form-control btn btn-primary">
      </div>
    </div>
  </form>
</div>

<table class="table table-striped search-results">
  <tbody>
    {% for result in results -%}
    <tr>
      <td class="column-icon">{{ result_icon(result) }}</td>
      <td class="column-type"><small>{{ result_type(result) }}</small></td>
      <td class="column-buttons">
        {{ result_title(result) }}
        <div class="pull-right">
          {{ result_buttons(result) }}
        </div>
      </td>
    </tr>
    {%- else -%}
    <tr>
      <td colspan="4">
      {% if search_text -%}
        {{ _('There were no results for your search... Sorry!') }}
      {%- else -%}
        {{ _('Please enter something in the search bar above.') }}
      {%- endif %}
      </td>
    </tr>
    {%- endfor %}
  </tbody>
</table>
{%- endblock %}


{% macro result_icon(result) -%}
{% if result.model == 'User' -%}
  <i class="icon-user" title="{{ _('Pilot') }}"></i>
{%- elif result.model == 'Club' -%}
  <i class="icon-group" title="{{ _('Club') }}"></i>
{%- elif result.model == 'Airport' -%}
  <i class="icon-map-marker" title="{{ _('Airport') }}"></i>
{%- endif %}
{%- endmacro %}

{% macro result_type(result) -%}
{% if result.model == 'User' -%}
  {{ _('Pilot') }}
{%- elif result.model == 'Club' -%}
  {{ _('Club') }}
{%- elif result.model == 'Airport' -%}
  {{ _('Airport') }}
{%- endif %}
{%- endmacro %}

{% macro result_title(result) -%}
{% if result.model == 'User' -%}
  <a href="{{ url_for('user.index', user_id=result.id) }}">{{ result.name|e }}</a>
{%- elif result.model == 'Club' -%}
  <a href="{{ url_for('club.index', club_id=result.id) }}">{{ result.name|e }}</a>
  <small>
  {% if result.website -%} - <a href="{{ result.website|e }}" target="_blank">{{ result.website|e }}</a>{%- endif %}
  </small>
{%- elif result.model == 'Airport' -%}
  <a href="{{ url_for('flights.airport', id=result.id) }}">{{ result.name|e }}</a>
  <small>
  {% if result.icao -%} - {{ result.icao|e }}{%- endif %}
  {% if result.frequency -%} - {{ '%.3f'|format(result.frequency|float) }} MHz{%- endif %}
  </small>
{%- endif %}
{%- endmacro %}

{% macro result_buttons(result) -%}
{% if result.model == 'User' -%}
  <a href="{{ url_for('flights.pilot', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-plane"></i> {{ _('Flights') }}</a>
  <a href="{{ url_for('statistics.index', page='pilot', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-bar-chart"></i> {{ _('Statistics') }}</a>
{%- elif result.model == 'Club' -%}
  <a href="{{ url_for('club.pilots', club_id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-group"></i> {{ _('Members') }}</a>
  <a href="{{ url_for('flights.club', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-plane"></i> {{ _('Flights') }}</a>
  <a href="{{ url_for('statistics.index', page='club', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-bar-chart"></i> {{ _('Statistics') }}</a>
{%- elif result.model == 'Airport' -%}
  <a href="{{ url_for('flights.airport', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-plane"></i> {{ _('Flights') }}</a>
  <a href="{{ url_for('statistics.index', page='airport', id=result.id) }}" class="btn btn-default btn-sm"><i class="icon-bar-chart"></i> {{ _('Statistics') }}</a>
{%- endif %}
{%- endmacro %}